baseURL: https://rada.support
languageCode: en-us
title: Поддержка Координационного совета
theme: default
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  summary: Поддержка Координационного совета
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
    image: logos/rada.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Поддержать координационный совет
    # Hero subtitle (optional)
    subtitle: Заполнить форму
    # Button text
    buttontext: Список организаций
    # Where the main hero button links to
    buttonlink: "/orgs"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Список организаций
    url: /orgs
  - title: Поддержать
    url: https://docs.google.com/forms/d/e/1FAIpQLSfe9z4v9FhrHCqQUOTgL6RpG6leAzuj0zL_-EmdcZTPzJpUQA/viewform
    button: true
  footer:
    # Logo (from /images/logos/___)
    logo: rada.svg
    socialmediatitle: Поделиться
    socialmedia:
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://www.facebook.com/belrada.vision/
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: telegram
    bulmalogo: true
    quicklinks:
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
