pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        agent {
            docker {
                image 'klakegg/hugo:0.74.3-ext-alpine'
                args '--entrypoint=\'\''
            }
        }
        steps {
            sh 'hugo'
        }
    }
    stage('Deploy') {
        agent {
            docker { image 'kissmy/ansistrano:latest'}
        }
        environment {
            SSH_DEPLOY_USER = credentials('SSH_DEPLOY_USER')
            SSH_PRIVATE_KEY  = credentials('SSH_PRIVATE_KEY')
            FRONTEND_HOST   = credentials('FRONTEND_HOST')
        }
        steps {
            writeFile file: 'infrastructure/hosts', text: """
${FRONTEND_HOST}
            """
            sh 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
            sh  'eval $(ssh-agent -s)'
            sh "echo \"$SSH_PRIVATE_KEY\" | ssh-add - "
            sh  'mkdir -p ~/.ssh'
            sh '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
            sh  "ansible-playbook -i infrastructure/hosts -u $SSH_DEPLOY_USER infrastructure/ansistrano_deploy.yml -v"
        }
    }
  }
}

