pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        agent {
            docker {
                image 'klakegg/hugo:0.74.3-ext-alpine'
                args '--entrypoint=\'\''
            }
        }
        steps {
            sh 'hugo'
        }
    }
    stage('Deploy') {
        agent {
            docker { image 'kissmy/ansistrano:latest'}
        }
        environment {
            SSH_DEPLOY_USER = credentials('SSH_DEPLOY_USER')
            SSH_PRIVATE_KEY  = credentials('SSH_PRIVATE_KEY')
            FRONTEND_HOST   = credentials('FRONTEND_HOST')
        }
        steps {
            writeFile file: 'infrastructure/hosts', text: """
${FRONTEND_HOST}
            """
            withCredentials([sshUserPrivateKey(credentialsId: "SSH_PRIVATE_KEY", keyFileVariable: 'SSH_KEY')]) {
               sh  "ansible-playbook --private-key=${SSH_KEY} -i infrastructure/hosts -u $SSH_DEPLOY_USER infrastructure/ansistrano_deploy.yml -v"
            }
        }
    }
  }
}

