pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        agent {
            docker {
                image 'klakegg/hugo:0.74.3-alpine'
                args '--entrypoint=\'\''
            }
        }
        steps {
            sh 'hugo'
        }
    }
    stage('Deploy') {
        agent {
            docker { image 'kissmy/ansistrano:latest'}
        }
        steps {
            sh 'ls -lh'
        }
    }
  }
}

